# -*- coding: utf-8 -*-
"""ИДЗ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tGA8epcmP_ro1fw4f7Lhdsq-fjxpUlan
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import seaborn as sns

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor

from google.colab import drive
drive.mount('/content/drive')

data = pd.read_csv('/content/drive/MyDrive/datasets/real_estate_dataset.csv')

print("Размер датасета:", data.shape)

print(data.info())
print("\nСтатистика:\n", data.describe())
print("\nПропуски:\n", data.isnull().sum())

plt.figure(figsize=(9, 6))
sns.histplot(data['Цена'], kde=True)
plt.title('Распределение цены недвижимости')
plt.show()

plt.figure(figsize=(9, 6))
numeric_data = data.select_dtypes(include=np.number)
sns.heatmap(numeric_data.corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Корреляционная матрица')
plt.show()

if 'Район' in data.columns:
    data = pd.get_dummies(data, columns=['Район'], drop_first=True)
    print("'Район' преобразован")
else:
    print("'Район' уже преобразован")

X = data.drop('Цена', axis=1)
y = data['Цена']

print(X.head())
print(y.head())

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""Линейная регрессия"""

lr = LinearRegression()
lr.fit(X_train, y_train)

pred_lr = lr.predict(X_test)

print("Линейная регрессия")
print("MAE =", mean_absolute_error(y_test, pred_lr))
print("RMSE =", np.sqrt(mean_squared_error(y_test, pred_lr)))
print("R2 =", r2_score(y_test, pred_lr))

"""Дерево решений"""

tree = DecisionTreeRegressor(random_state=42)

tree.fit(X_train, y_train)

pred_tree = tree.predict(X_test)

print("Дерево решений")
print("MAE =", mean_absolute_error(y_test, pred_tree))
print("RMSE =", np.sqrt(mean_squared_error(y_test, pred_tree)))
print("R2 =", r2_score(y_test, pred_tree))

"""Random Forest"""

forest = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

forest.fit(X_train, y_train)

pred_forest = forest.predict(X_test)

print("Random Forest")
print("MAE =", mean_absolute_error(y_test, pred_forest))
print("RMSE =", np.sqrt(mean_squared_error(y_test, pred_forest)))
print("R2 =", r2_score(y_test, pred_forest))

"""Gradient Boosting"""

gbr = GradientBoostingRegressor(
    n_estimators=200,
    learning_rate=0.1,
    random_state=42
)

gbr.fit(X_train, y_train)

pred_gbr = gbr.predict(X_test)

print("Gradient Boosting")
print("MAE =", mean_absolute_error(y_test, pred_gbr))
print("RMSE =", np.sqrt(mean_squared_error(y_test, pred_gbr)))
print("R2 =", r2_score(y_test, pred_gbr))

"""Сравнение моделей"""

results = pd.DataFrame({
    'Модель': [
        'Линейная регрессия',
        'Дерево решений',
        'Random Forest',
        'Gradient Boosting'
    ],
    'MAE': [
        mean_absolute_error(y_test, pred_lr),
        mean_absolute_error(y_test, pred_tree),
        mean_absolute_error(y_test, pred_forest),
        mean_absolute_error(y_test, pred_gbr)
    ],
    'RMSE': [
        np.sqrt(mean_squared_error(y_test, pred_lr)),
        np.sqrt(mean_squared_error(y_test, pred_tree)),
        np.sqrt(mean_squared_error(y_test, pred_forest)),
        np.sqrt(mean_squared_error(y_test, pred_gbr))
    ],
    'R2': [
        r2_score(y_test, pred_lr),
        r2_score(y_test, pred_tree),
        r2_score(y_test, pred_forest),
        r2_score(y_test, pred_gbr)
    ]
})

results = results.sort_values(by='R2', ascending=False)

results

"""График сравнения"""

plt.figure(figsize=(10, 5))

plt.bar(results['Модель'], results['R2'])

plt.title('Сравнение моделей по R²')
plt.ylabel('R²')
plt.xticks(rotation=20)

plt.show()